package com.investrocket.audit;

public enum AuditAction {
    USER_REGISTERED,
    USER_LOGGED_IN,
    PROFILE_UPDATED,
    PASSWORD_CHANGED,
    ORDER_PLACED,
    ORDER_CANCELLED,
    TRADE_EXECUTED,
    WATCHLIST_ADDED,
    WATCHLIST_REMOVED,
    SIMULATOR_RESET,
    RISK_SETTINGS_UPDATED,
    SNAPSHOT_CREATED
}
