package com.investrocket.audit;

public enum AuditAction {
    USER_REGISTERED,
    USER_LOGGED_IN,
    PROFILE_UPDATED,
    PASSWORD_CHANGED,
    ORDER_PLACED,
    ORDER_CANCELLED,
    TRADE_EXECUTED,
    WATCHLIST_ADDED,
    WATCHLIST_REMOVED,
    SIMULATOR_RESET,
    RISK_SETTINGS_UPDATED,
    SNAPSHOT_CREATED,
    ADMIN_BOOTSTRAPPED,
    ADMIN_USER_UPDATED,
    ADMIN_USER_ENABLED,
    ADMIN_USER_DISABLED,
    PRICE_ALERT_CREATED,
    PRICE_ALERT_TRIGGERED,
    PRICE_ALERT_CANCELLED,
    JOURNAL_ENTRY_CREATED,
    JOURNAL_ENTRY_UPDATED,
    JOURNAL_ENTRY_DELETED
}
